### ISSUE TITLE
Computed property names for methods in class literals transpile incorrectly

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#127]
```ts
class Test {
  destroy() {
    print('gone')
  }

  ['s'] = this.destroy
}
```

```lua
-- snip
Test.constructor = function(self, ...)
		self.['s'] = self.destroy; -- <<< bug
		return self;
	end;
```

**Comment by Validark** [comment]
This is fixed now.

**Comment by evaera** [comment]
> This is fixed now.

This issue is not fixed on latest master. New error, now:
```ts
class Test {
  destroy() {
    print('gone')
  }

  ['test'] = this.destroy
}
```

` Transpiler Error: Cannot use '['test']' as identifier (doesn't match Lua's identifier rules)`

**Comment by Validark** [comment]
Well, it doesn't transpile incorrectly anymore.

**Comment by evaera** [comment]
This is still incorrect behavior, though. Computed property names in TS should translate to computed property names in Lua. Identifier rules don't apply in this case.
